#!/bin/bash
sudo apt-get -y update
git clone https://github.com/s-rostami/build.git
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt install -y nginx
sudo service nginx start
#copying default file:
cd /home/ubuntu/build/
sudo cp default /etc/nginx/sites-available/default
sudo service nginx restart

